#!/usr/bin/env bash
#displays numbers from 1 - 20 with message at specefic iterations
#"bad luck from China" 4th
#"bad luck from Japan" 9th
#"bad luck from Italy" 17th

count=1

while [ $count -le 20 ]
do
  echo "$count"
  case $count in
    "4") echo "bad luck from China";;
    "9") echo "bad luck from Japan";;
    "17") echo "bad luck from Italy";;
  esac
  (( count++ ))
done
