#!/usr/bin/env bash
#displays time from 0:01 to 12:59 in increments of 1min
#displays hrs from 0-12
#displays minutes from 1-59

hour=0

while [ $hour -le 12 ]
do
  echo "Hour: $hour"
  minute=1
  while [ $minute -le 59 ]
  do
    printf "%02d\n" "$minute"
    (( minute++ ))
  done
  (( hour++ ))
done
